server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
spring:
#    profiles:
#      active: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 10
      max-idle: 2
      min-idle: 2
      initial-size: 5
      remove-abandoned: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

